### ISSUE TITLE
Can't build on raspbian

### ISSUE THREAD

**Issue by aacn14521** [PelionIoT/mbed-edge#24]
Hi,

I wanted to run mbed-edge on raspbian, and I built it as follows, but the error occurred as follows.
How can I solve it?

==== executed command ====
udo apt-get -y update
sudo apt-get -y install libc6-dev
sudo apt-get -y install libmosquitto-dev mosquitto-clients
sudo apt-get -y install build-essential cmake git doxygen graphviz
git clone https://github.com/ARMmbed/mbed-edge/
cd mbed-edge
#git submodule update --init --recursive
git submodule init
git submodule update
mkdir build
cd build
cat <<EOF > toolchain_file
set(CMAKE_MAKE_PROGRAM make)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
EOF
cmake -DCMAKE_TOOLCHAIN_FILE=toolchain_file -DDEVELOPER_MODE=ON -DFIRMWARE_UPDATE=OFF ..
make
====

==== error ====
cmake -DCMAKE_TOOLCHAIN_FILE=toolchain_file -DDEVELOPER_MODE=ON -DFIRMWARE_UPDATE=OFF ..
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc
CMake Error: Generator: execution of make failed. Make command was: "" "cmTC_5fedb/fast"
-- Check for working C compiler: /usr/bin/gcc -- broken
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/src/pelion/mbed-edge/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"" "cmTC_5fedb/fast"
    No such file or directory
    Generator: execution of make failed. Make command was: "" "cmTC_5fedb/fast"
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:28 (project)

-- Configuring incomplete, errors occurred!
See also "/home/pi/src/pelion/mbed-edge/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/src/pelion/mbed-edge/build/CMakeFiles/CMakeError.log".
====

  Thank you.

**Comment by cmonr** [comment]
@aacn14521 Why was this line commented out?

>  #git submodule update --init --recursive

I don't think `git submodule update` implies `--recursive`.

However, I also don't think that building on Raspbian is supported.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-1070

**Comment by ygoyal18** [comment]
Raspbian is not a supported platform. To build mbed-edge (part of Pelion Edge) for RPi, please follow the project - https://github.com/armPelionEdge/meta-pelion-edge
