### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by cvasilak** [PelionIoT/mbed-edge#27]
Hello all,

am trying to build the project (latest [master](https://github.com/ARMmbed/mbed-edge/commit/1d681cd114d91af25947d2505fa7350d35e87565)) but during CMake, some errors occur and make fails.

Using an `Ubuntu 16.04.7 LTS (Xenial Xerus)` machine with all the dependencies as specified by the instructions installed.

Further the '`config/` directory is filled with the required credentials `mbed_cloud_dev_credentials.c` and `update_default_resources.c`

Command line:
```
cmake -DTRACE_LEVEL=DEBUG -DDEVELOPER_MODE=ON -DFIRMWARE_UPDATE=ON -DEDGE_REGISTERED_ENDPOINT_LIMIT=100 -DEDGE_PRIMARY_NETWORK_INTERFACE_ID=ens33 ..
```

Output of CMake:
[CMake Output](https://gist.github.com/cvasilak/4874a681d9840874cb5295b4ee0f3172)

and the log files:
[CmakeError.log](https://gist.github.com/cvasilak/5f8d6975ddcdf5777e9b2be92584a8a2)
[CMakeOutput.log](https://gist.github.com/cvasilak/5ec75633b0e7920f79889f65926ae486)

Let me know if you need more information.

Thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-1073

**Comment by JanneKiiskila** [comment]
I recommend using the docker, seems the server version has some libs difference.
